# version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: transit
      POSTGRES_USER: transit
      POSTGRES_PASSWORD: transit123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db

  #
  app:
    build: .
    depends_on:
      - db
    environment:
      PGHOST: db           # 指向同一個 compose network 上的 db 服務
      PGPORT: "5432"
      PGUSER: transit
      PGPASSWORD: transit123
      PGDATABASE: transit
    volumes:
      - ./data:/app/data:ro
      - ./schema.sql:/app/schema.sql:ro
      - ./load_data.py:/app/load_data.py:ro
      - ./queries.py:/app/queries.py:ro
      - ./requirements.txt:/app/requirements.txt:ro

volumes:
  pgdata: